// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9J2L5pXzSra02q64NiQm5QwYC6xr58Dc',
    appId: '1:653168814681:web:56bc08425b76040deadf48',
    messagingSenderId: '653168814681',
    projectId: 'flutter-crud-bd43f',
    authDomain: 'flutter-crud-bd43f.firebaseapp.com',
    storageBucket: 'flutter-crud-bd43f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIhPRvXmfyFUnJW2y28hxCxdOYTYgLmo0',
    appId: '1:653168814681:android:89030539fcd3b2caeadf48',
    messagingSenderId: '653168814681',
    projectId: 'flutter-crud-bd43f',
    storageBucket: 'flutter-crud-bd43f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6UuDNs92MwNAyKsAAzGSw2ujj522pCng',
    appId: '1:653168814681:ios:05fddc9e05772a65eadf48',
    messagingSenderId: '653168814681',
    projectId: 'flutter-crud-bd43f',
    storageBucket: 'flutter-crud-bd43f.appspot.com',
    iosClientId: '653168814681-cn31gtf3uhr9vq2q3trk7mu3m5314r4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudFirestone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6UuDNs92MwNAyKsAAzGSw2ujj522pCng',
    appId: '1:653168814681:ios:05fddc9e05772a65eadf48',
    messagingSenderId: '653168814681',
    projectId: 'flutter-crud-bd43f',
    storageBucket: 'flutter-crud-bd43f.appspot.com',
    iosClientId: '653168814681-cn31gtf3uhr9vq2q3trk7mu3m5314r4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudFirestone',
  );
}
